### PR TITLE
Fix IME entry in Stride

### LINKED ISSUE #2335: Chinese input problem in Stride
Observed on Windows, using Chinese IME: in Stride, if we try to use the IME for Chinese, the IME won't show up in some slots, for example a type or value slot.
Here is an example typing "ku" in 2 different slots of a var assign showing the difference: in the type slot, the IME do not show but the latin letter is shown, and text is duplicated and mirrored.
image

image

### PR DESCRIPTION
**Pull request by neilccbrown**
We discovered that IME wasn't working in Stride, because we process edit events differently there, and it was interfering with how IME works.  This change handles IME events ourselves so that we can separate it from all of Stride's unique processing of edits.

Fixes #2335

### CODE REVIEW

File: bluej/src/main/java/bluej/utility/javafx/DelegableScalableTextField.java [hunk 1]
```diff
@@ -63,18 +72,40 @@ public class DelegableScalableTextField<DELEGATE_IDENT> extends ScalableHeightTe
 
     private final TextFieldDelegate<DELEGATE_IDENT> delegate;
     private final DELEGATE_IDENT delegateId;
+
+    // Keep track of InputMethod (IM) positions, e.g. for entering Chinese with
```
Comment (PwtKCL) [inline bluej/src/main/java/bluej/utility/javafx/DelegableScalableTextField.java:76]: This is very subtle and not critical for the code, but I would try to use another word than "positions", because at first, I thought it mean the "UI" position of the IME tool (like where it displays relative to the slot, or something of that nature).
Maybe just "InputMethod (IM) text's positions" clarifies that.

File: bluej/src/main/java/bluej/utility/javafx/DelegableScalableTextField.java [hunk 2]
```diff
@@ -63,18 +72,40 @@ public class DelegableScalableTextField<DELEGATE_IDENT> extends ScalableHeightTe
...
+    // the on-screen IME keyboard.  imStart is the start of the current sequence of
+    // "composing" characters that could end up staying as English or transformed into
```
Comment (PwtKCL) [inline bluej/src/main/java/bluej/utility/javafx/DelegableScalableTextField.java:78]: If I understood it right, shall we specify "imStart is the start [..] _in the current text slot_."

File: bluej/src/main/java/bluej/utility/javafx/DelegableScalableTextField.java [hunk 3]
```diff
@@ -315,11 +430,56 @@ public void changed(ObservableValue<? extends Number> observable, Number oldValu
         addEventHandler(KeyEvent.KEY_PRESSED, e -> { if (e.getCode() == KeyCode.ESCAPE) delegate.escape(); });
         
     }
+
+    @OnThread(Tag.FXPlatform)
+    private void handleInputMethodEvent(InputMethodEvent event) {
+        // This is adapted from the default handler in TextInputControlSkin.  That handler
+        // uses selection to keep track of some things.  We keep track manually here but
+        // there is not currently a visual representation of the highlight.
```
Comment (PwtKCL) [inline bluej/src/main/java/bluej/utility/javafx/DelegableScalableTextField.java:438]: I don't understand this very last sentence - is it something that the default method would do but we don't (and does it matter?)

**Review by PwtKCL — COMMENTED** [review]
Well done for this tricky changes in Stride (and working out with the IMEs !).
I've made a few comments about the comments for some clarification but code wise, everything seems good and the branch can be merged.
